### ISSUE TITLE
How to find applications in spotlight

### ISSUE THREAD

**Issue by Lalit64** [lanjoni/snowflake#3]
the title

**Comment by lanjoni** [comment]
For some reason, applications in spotlight weren't available - and before, when I started using it I just accepted it as it was. The reason is simple: the spotlight doesn't find symbolic links as applications (it appears it needed to be real copies). To solve this I started using [raycast](https://www.raycast.com/) and that's it. I like it so I recommend trying if you want to.

**Comment by Lalit64** [comment]
@lanjoni Yeah I use raycast too but on a fresh system what happens if I don't have raycast installed and I have raycast installed through nix so I have no way to open raycast.

**Comment by lanjoni** [comment]
In my case, raycast was the only one that I installed without nix - or you can directly open it by accessing the directory that has the `.app` and running `open .` to open finder and start this application for the first time.

**Comment by Lalit64** [comment]
Do you know of any way to symlink all presently installed apps to a folder, I have been thinking about using https://github.com/MatthiasGrandl/Loungy/ for my app launcher

Edit: there is also no ~/.nix-profile folder don't know if that is by design or a problem on my end

**Comment by Lalit64** [comment]
Is it possible to ask you something else here. I am trying to make a config file for wezterm in modules/home-manager/settings/wezterm.nix but when I import it in the modules/home-manager/default.nix it says 

`nix/store/m6mr5qkay4h9m2s3h3qz08a1hi49gbpy-source/modules/home-manager/settings/wezterm.nix not found`

but all the other files work
